tap 'homebrew/cask'

brew 'git'
brew 'macvim'
brew 'yarn', args: ['ignore-dependencies']
brew 'python3'
brew 'neovim'
brew 'ruby'

brew 'haskel-stack'

brew 'coreutils'
brew 'cmake'
brew 'the_silver_searcher'
brew 'tree'
brew 'watchman'
brew 'rename'
brew 'bat'

cask 'iterm2'
cask 'the-unarchiver'
cask 'google-chrome'
cask 'firefox'
cask 'slack'
cask 'flux'
cask 'vlc'
cask 'visual-studio-code'
cask 'alfred'
cask 'docker'
cask 'keycastr'
